version: "3.8"
services:
  backend:
    build: 
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "3000:3000"
    networks:
      - pill
    restart: on-failure
    depends_on:
      - db
  frontend:
    build: 
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "5173:5173"
    networks:
      - pill
    depends_on:
      - backend
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'pill_technical_test'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - pill
networks:
  pill:
    driver: bridge
